USE university_db;


CREATE TABLE STUDENT (
    Name VARCHAR(50),
    Student_number INT PRIMARY KEY,
    Class INT,
    Major VARCHAR(50)
);

CREATE TABLE COURSE (
    Course_name VARCHAR(100),
    Course_number VARCHAR(10) PRIMARY KEY,
    Credit_hours INT,
    Department VARCHAR(50)
);

CREATE TABLE SECTION (
    Section_identifier INT PRIMARY KEY,
    Course_number VARCHAR(10),
    Semester VARCHAR(10),
    Year INT,
    Instructor VARCHAR(50),
    FOREIGN KEY (Course_number) REFERENCES COURSE(Course_number)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE GRADE_REPORT (
    Student_number INT,
    Section_identifier INT,
    Grade CHAR(1),
    PRIMARY KEY (Student_number, Section_identifier),
    FOREIGN KEY (Student_number) REFERENCES STUDENT(Student_number)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Section_identifier) REFERENCES SECTION(Section_identifier)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PREREQUISITE (
    Course_number VARCHAR(10),
    Prerequisite_number VARCHAR(10),
    PRIMARY KEY (Course_number, Prerequisite_number),
    FOREIGN KEY (Course_number) REFERENCES COURSE(Course_number)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Prerequisite_number) REFERENCES COURSE(Course_number)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- STUDENT
INSERT INTO STUDENT VALUES ('Smith', 17, 1, 'CS');
INSERT INTO STUDENT VALUES ('Brown', 8, 2, 'CS');

-- COURSE
INSERT INTO COURSE VALUES ('Intro to Computer Science', 'CS1310', 4, 'CS');
INSERT INTO COURSE VALUES ('Data Structures', 'CS3320', 4, 'CS');
INSERT INTO COURSE VALUES ('Discrete Mathematics', 'MATH2410', 3, 'MATH');
INSERT INTO COURSE VALUES ('Database', 'CS3380', 3, 'CS');

-- SECTION
INSERT INTO SECTION VALUES (85, 'MATH2410', 'Fall', 2007, 'King');
INSERT INTO SECTION VALUES (92, 'CS1310', 'Fall', 2007, 'Anderson');
INSERT INTO SECTION VALUES (102, 'CS3320', 'Spring', 2008, 'Knuth');
INSERT INTO SECTION VALUES (112, 'MATH2410', 'Fall', 2008, 'Chang');
INSERT INTO SECTION VALUES (119, 'CS1310', 'Fall', 2008, 'Anderson');
INSERT INTO SECTION VALUES (135, 'CS3380', 'Fall', 2008, 'Stone');

-- GRADE_REPORT
INSERT INTO GRADE_REPORT VALUES (17, 112, 'B');
INSERT INTO GRADE_REPORT VALUES (17, 119, 'C');
INSERT INTO GRADE_REPORT VALUES (8, 85, 'A');
INSERT INTO GRADE_REPORT VALUES (8, 92, 'A');
INSERT INTO GRADE_REPORT VALUES (8, 102, 'B');
INSERT INTO GRADE_REPORT VALUES (8, 135, 'A');

-- PREREQUISITE
INSERT INTO PREREQUISITE VALUES ('CS3380', 'CS3320');
INSERT INTO PREREQUISITE VALUES ('CS3380', 'MATH2410');
INSERT INTO PREREQUISITE VALUES ('CS3320', 'CS1310');

INSERT INTO STUDENT VALUES ('Johnson', 25, 1, 'Math');

UPDATE STUDENT
SET Class = 2
WHERE Name = 'Smith';

INSERT INTO COURSE VALUES ('Knowledge Engineering', 'CS4390', 3, 'CS');

DELETE FROM STUDENT 
WHERE
    Student_number = 17;
